vich_uploader:
    db_driver: orm

    mappings:
        produto_imagem:
            uri_prefix: /images/produtos
            upload_destination: '%kernel.project_dir%/public/images/produtos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: app.utils.estoque.vich_uploader_produto_directory_namer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
